block: prep/background
date: '2022022612'
experiment: TEST_assim
geometry: GrandesRousses250m
kind: PREP
local: /home/imperatoren/work/edelweiss_assimilation/data/[geometry:tag]/[experiment]/mb[member]/prep/background/PREP_[date:ymdh].nc
member:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
model: surfex
namebuild: flat@cen
namespace: vortex.multi.fr
username: imperatoren
vapp: edelweiss
vconf: '[geometry:tag]'
