block: meteo
date: '[dateend]'
datebegin: '2021080106'
dateend: '2022080106'
experiment: ALPAGA
username: vernaym
geometry: GrandesRousses250m
kind: MeteorologicalForcing
filename: /home/imperatoren/work/edelweiss_assimilation/data/[geometry:tag]/forcing/[experiment]/mb0[member]/meteo/FORCING_[datebegin]_[dateend].nc
member:
- 10
- 11
- 12
- 13
- 14
- 15
- 16

namebuild: flat@cen
namespace: vortex.multi.fr
vapp: edelweiss
vconf: '[geometry:tag]'
vortex1: True # This is useful for basename: when True, filename is FORCING_datebegin_dateend.nc, else FORCING.geometry_datebegin_dateend.nc